@startuml

class EchoEndpoint <<Path>> {
 +echo(msg)
 +echoWithJWTToken(msg) << @JWTTokenNeeded >>
}

class User <<Entity>> {
 -id <<@Id>>
 -lastName
 -firstName
 -login
 -password
}

class UserEndpoint <<Path>> {
 +authenticateUser(login, password)
}

class JWTTokenNeededFilter <<@JWTTokenNeeded>> implements ContainerRequestFilter {
 +filter(containerRequestContext)
}

UserEndpoint ..> User

@enduml